# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
##
name: Node.js CI
env: 
  AWS_ACCESS_KEY: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS: ${{ secrets.aws_secret_access }}
  DEFAULT_REGION: ${{ secrets.default_region }}
  MY_BUCKET: ${{ secrets.my_bucket }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name : Build artifact
    runs-on: ubuntu-latest

    #strategy:
     # matrix:
       # node-version: [10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    #- run: npm ci
    - run: npm install
    - run: CI='' npm run build --prod
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with: 
          name: artifact
          path: build
  deploy:
     name: Deploy artifact
     runs-on: ubuntu-latest
     needs: build
     steps:
     - name : Downloading artifact
       uses: actions/download-artifact@v2
       with:
        name: artifact
        #aws s3api put-object-tagging --bucket MY_BUCKET --key build_$GITHUB_WORKFLOW_$GITHUB_RUN_ID.tar --tagging '{"TagSet": [{ "Key": "designation", "Value": "confidential" }]}'
     - run : |
              cd ..
              tar zcf build.tar digichlist-Admin-UI/ 
              aws configure set aws_access_key_id "$AWS_ACCESS_KEY"
              aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS"
              aws configure set default.region "$DEFAULT_REGION"
              aws s3 cp build.tar "s3://$MY_BUCKET/build_$GITHUB_WORKFLOW_$GITHUB_RUN_ID.tar"
      
              
              

